version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Globally install grunt-cli
          command: sudo npm install -g grunt-cli
      - run:
          name: Run linter
          command: grunt lint
      - run:
          name: Run unit tests
          command: npm test
  deploy:
    version: 2
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b0:ec:cf:cc:99:48:ac:46:5f:a1:eb:61:0d:c3:c2:26"
      - setup_remote_docker
      - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Globally install grunt-cli
          command: sudo npm install -g grunt-cli
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Create mongodbConfig.json
          command: grunt createDbConfig --user=$MONGO_USER --pass=$MONGO_PASSWORD --hosts=$MONGO_HOSTS --opts=$MONGO_OPTIONS
      - run:
          name: Log into Docker
          command: |
            docker login --email=_ --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
      - run:
          name: Push image to DockerHub
          command: |
            docker build -t registry.heroku.com/playspark/web .
            docker push registry.heroku.com/playspark/web
workflows:
  version: 2
  release_to_heroku:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master