version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run unit tests
          command: npm test
  deploy:
    version: 2
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: docker build -t project-backend:$CIRCLE_SHA1
      - run:
          name: Push image to DockerHub
          command: |
            docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_PASSWORD
            docker push project-backend:$CIRCLE_SHA
      - run:
          name: Setup Heroku
          command: |
            chmod +x .circleci/setup-heroku.sh
            .circleci/setup-heroku.
      - run:
          name: Deploy to Heroku
          command: |
            cd app/
            git push heroku master
workflows:
  version:2
  deploy_master:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only: master